const ideias = {
  frontend: {
    junior: [
       "Página de perfil pessoal",
  "Portfólio pessoal com HTML, CSS e JS puro",
  "Página de receitas",
  "Blog estático",
  "Página de login (sem backend)",
  "Calculadora simples",
  "Relógio digital",
  "Conversor de temperatura",
  "Lista de tarefas (To-do list)",
  "Conversor de moedas (valores fixos)",
  "Clone da página inicial do Google",
  "Página com grid de cards responsivos",
  "Galeria de imagens com modal",
  "Página com animações CSS",
  "Landing page responsiva com animações CSS",
  "Página com dark mode toggle",
  "Página com layout mobile-first",
  "Página com formulário estilizado",
  "Página com barra de navegação fixa",
  "Página com efeito parallax",
  "Jogo da velha",
  "Jogo de memória",
  "Quiz interativo com JavaScript e feedback visual",
  "Simulador de dados de formulário",
  "Validação de formulário",
  "Contador regressivo",
  "Gerador de senhas",
  "Simulador de sorteio",
  "Página com tabs interativas",
  "Página com contador de cliques",
  "Página com Bootstrap",
  "Página com Tailwind CSS",
  "Página com jQuery",
  "Página com Font Awesome",
  "Página com animações GSAP",
  "Página com Chart.js",
  "Página com ícones SVG animados",
  "Página com scroll suave",
  "Página com tooltips",
  "Página com pop-ups",
  "Página com drag and drop",
  "Página com barra de progresso",
  "Página com notificações",
  "Página com tema dinâmico",
  "Tema claro/escuro com persistência via localStorage",
  "Página com menu hamburguer",
  "Página com loading spinner",
  "Página com cards flip",
  "Página com efeito hover",
  "Página com botão que muda cor",
  "Simulador de app de clima (dados fixos)",
  "Simulador de app de notas",
  "Simulador de app de pomodoro",
  "Simulador de app de lista de compras",
  "Simulador de app de hábitos",
  "Simulador de app de calendário",
  "Simulador de app de finanças pessoais",
  "Simulador de app de leitura",
  "Simulador de app de música (sem áudio)",
  "Simulador de app de mensagens (estático)",
  "Modal customizado",
  "Tooltip customizado",
  "Accordion",
  "Tabs",
  "Slider",
  "Dropdown",
  "Menu lateral",
  "Card interativo",
  "Botão animado",
  "Input com máscara",
  "App que mostra piadas (API de piadas)",
  "App que mostra frases motivacionais",
  "App que mostra imagens de gatos",
  "App que mostra dados de Pokémon",
  "App que mostra dados de filmes",
  "App que mostra dados de países",
  "App que mostra dados de usuários",
  "App que mostra dados de livros",
  "App que mostra dados de moedas",
  "App que mostra dados de clima (API aberta)",
  "Projeto com estrutura de pastas organizada",
  "Projeto com README explicativo",
  "Projeto com favicon e manifest",
  "Projeto com semântica HTML",
  "Projeto com acessibilidade básica",
  "Projeto com SEO básico",
  "Projeto com layout flexbox",
  "Projeto com layout grid",
  "Projeto com media queries",
  "Projeto com variáveis CSS",
  "Página com easter egg escondido",
  "Página com tema retrô",
  "Página com tema futurista",
  "Página com tema minimalista",
  "Página com tema cyberpunk",
  "Página com tema natureza",
  "Página com tema espacial",
  "Página com tema de games",
  "Página com tema de filmes",
  "Página com tema de anime"

    ],
    pleno: [
      "Dashboard com gráficos dinâmicos usando Chart.js",
      "Aplicativo com React e consumo de API pública",
      "Sistema de busca com filtros e paginação",
      "Gerenciador de tarefas com drag-and-drop",
      "Navegação SPA com React Router e animações",
      "Dashboard interativo com gráficos usando Chart.js",
  "Sistema de autenticação com Firebase",
  "CRUD completo com React e API REST",
  "Aplicativo de clima com consumo de API externa",
  "Gerenciador de tarefas com React e localStorage",
  "Blog com React Router e Markdown",
  "Sistema de favoritos com persistência em IndexedDB",
  "Clone do Instagram com React e Firebase",
  "Aplicativo de receitas com filtros e busca",
  "Simulador de investimentos com gráficos dinâmicos",
  "E-commerce com carrinho e cálculo de frete",
  "Sistema de comentários com autenticação",
  "App de leitura com modo noturno e bookmarking",
  "App de quiz com ranking e pontuação",
  "App de notas com categorias e busca",
  "App de calendário com eventos recorrentes",
  "App de hábitos com gamificação",
  "App de finanças com gráficos e metas",
  "App de filmes com busca e favoritos",
  "App de livros com reviews e notas",
  "Landing page com animações GSAP e scroll reveal",
  "Site institucional com CMS headless (ex: Strapi)",
  "Portfólio com React e animações framer-motion",
  "Página com formulário validado via Yup",
  "Página com integração com API de pagamentos",
  "Página com integração com API de localização",
  "Página com integração com API de tradução",
  "Página com integração com API de imagens",
  "Página com integração com API de música",
  "Página com integração com API de vídeos",
  "Página com integração com API de notícias",
  "Página com integração com API de esportes",
  "Página com integração com API de criptomoedas",
  "Página com integração com API de transporte público",
  "Página com integração com API de previsão do tempo",
  "Página com integração com API de dados públicos",
  "Página com integração com API de redes sociais",
  "Página com integração com API de inteligência artificial",
  "Página com integração com API de geolocalização",
  "Página com integração com API de saúde",
  "Página com integração com API de educação",
  "Sistema de login com OAuth (Google, GitHub)",
  "Sistema de cadastro com validação de senha forte",
  "Sistema de recuperação de senha",
  "Sistema de upload de arquivos com preview",
  "Sistema de envio de e-mails com integração externa",
  "Sistema de notificações push",
  "Sistema de temas dinâmicos com context API",
  "Sistema de internacionalização (i18n)",
  "Sistema de acessibilidade com ARIA",
  "Sistema de SEO com React Helmet",
  "Sistema de roteamento dinâmico com React Router",
  "Sistema de lazy loading de componentes",
  "Sistema de infinite scroll",
  "Sistema de paginação de dados",
  "Sistema de filtros avançados",
  "Sistema de busca com debounce",
  "Sistema de autocomplete",
  "Sistema de drag and drop com react-beautiful-dnd",
  "Sistema de formulários com React Hook Form",
  "Sistema de testes com Jest e Testing Library",
  "Sistema de deploy com Vercel ou Netlify",
  "Sistema de CI/CD com GitHub Actions",
  "Sistema de versionamento com Git e GitHub",
  "Sistema de documentação com Storybook",
  "Sistema de design system com componentes reutilizáveis",
  "Sistema de gerenciamento de estado com Redux",
  "Sistema de gerenciamento de estado com Zustand",
  "Sistema de gerenciamento de estado com Context API",
  "Sistema de gerenciamento de estado com Recoil",
  "Sistema de gerenciamento de estado com MobX",
  "Sistema de gerenciamento de dados com SWR",
  "Sistema de gerenciamento de dados com React Query",
  "Sistema de gerenciamento de dados com Axios",
  "Sistema de gerenciamento de dados com Fetch API",
  "Sistema de gerenciamento de dados com GraphQL",
  "Sistema de gerenciamento de dados com Apollo Client",
  "Sistema de gerenciamento de dados com Firebase",
  "Sistema de gerenciamento de dados com Supabase",
  "Sistema de gerenciamento de dados com PocketBase",
  "Sistema de gerenciamento de dados com Hasura",
  "Sistema de gerenciamento de dados com Prisma",
  "Sistema de gerenciamento de dados com MongoDB Atlas",
  "Sistema de gerenciamento de dados com SQLite",
  "Sistema de gerenciamento de dados com PostgreSQL",
  "Sistema de gerenciamento de dados com MySQL",
  "Sistema de gerenciamento de dados com FaunaDB",
  "Sistema de gerenciamento de dados com Airtable",
  "Sistema de gerenciamento de dados com Google Sheets",
  "Sistema de gerenciamento de dados com LocalStorage",
  "Sistema de gerenciamento de dados com IndexedDB",
  "Sistema de gerenciamento de dados com Cookies",
  "Sistema de gerenciamento de dados com SessionStorage",
  "Sistema de gerenciamento de dados com WebSockets",
  "Sistema de gerenciamento de dados com SSE",
  "Sistema de gerenciamento de dados com REST",
  "Sistema de gerenciamento de dados com RPC",
  "Sistema de gerenciamento de dados com JSON Server",
  "Sistema de gerenciamento de dados com MirageJS",
  "Sistema de gerenciamento de dados com MSW (Mock Service Worker)",
  "Sistema de gerenciamento de dados com Firebase Emulator",
  "Sistema de gerenciamento de dados com GraphQL Mock",
  "Sistema de gerenciamento de dados com API externa simulada"

    ],
    senior: [
      "SPA com autenticação OAuth2 e gerenciamento de sessão",
      "Editor de código online com destaque de sintaxe",
      "PWA com cache offline, notificações push e instalação",
      "Visualizador de dados em tempo real com WebSocket",
      "Testes automatizados com Cypress e integração contínua"
    ]
  },
  backend: {
    junior: [
      "API REST com Node.js e Express",
      "CRUD simples com SQLite e validação básica",
      "Sistema de login com hash de senha (bcrypt)",
      "Gerador de senhas seguras via terminal",
      "API de clima que consome dados externos"
    ],
    pleno: [
      "Autenticação com JWT e refresh token",
      "Sistema de agendamento com PostgreSQL",
      "API com testes automatizados usando Jest",
      "Monitoramento de logs com Winston e Morgan",
      "Upload de arquivos com validação e armazenamento local"
    ],
    senior: [
      "Microserviços com Docker, Kafka e PostgreSQL",
      "Sistema de filas com RabbitMQ e workers",
      "API GraphQL com resolvers complexos",
      "Search engine com ElasticSearch",
      "Testes de carga com Artillery e métricas com Prometheus"
    ]
  },
  fullstack: {
    junior: [
      "To-do list com React no front e Express no back",
      "Blog com painel admin básico e Markdown",
      "Sistema de login com validação e sessões",
      "App de receitas com upload de imagens",
      "Calculadora financeira com histórico"
    ],
    pleno: [
      "E-commerce com carrinho, login e banco de dados",
      "Plataforma de cursos com upload de vídeos",
      "Sistema de comentários com moderação",
      "Painel administrativo com gráficos e filtros",
      "Chat em tempo real com WebSocket"
    ],
    senior: [
      "Plataforma de ensino com pagamentos, vídeos e painel admin",
      "Sistema de autenticação com 2FA e recuperação de senha",
      "App com CI/CD, testes automatizados e deploy em cloud",
      "CMS customizado com editor visual e controle de acesso",
      "Fullstack app com microserviços, cache, e escalabilidade horizontal"
    ]
  }
};

// Mapeamento de ícones por área
const icones = {
  frontend: "fa-paint-brush",
  backend: "fa-server",
  fullstack: "fa-layer-group"
};

function gerarIdeia() {
  const area = document.getElementById("area").value;
  const nivel = document.getElementById("nivel").value;

  const lista = ideias[area][nivel];
  const ideiaTexto = lista[Math.floor(Math.random() * lista.length)];
  const icone = icones[area];

  const ideiaHTML = `
    <i class="fas ${icone}" style="color:#00bcd4; margin-right:8px;"></i>
    <strong>${nivel.toUpperCase()} - ${area.toUpperCase()}</strong>: ${ideiaTexto}
  `;

  document.getElementById("ideia").innerHTML = ideiaHTML;
}