const ideias = {
  frontend: {
    junior: [
      "Página de perfil pessoal",
      "Portfólio pessoal com HTML, CSS e JS puro",
      "Página de receitas",
      "Blog estático",
      "Página de login (sem backend)",
      "Calculadora simples",
      "Relógio digital",
      "Conversor de temperatura",
      "Lista de tarefas (To-do list)",
      "Conversor de moedas (valores fixos)",
      "Clone da página inicial do Google",
      "Página com grid de cards responsivos",
      "Galeria de imagens com modal",
      "Página com animações CSS",
      "Landing page responsiva com animações CSS",
      "Página com dark mode toggle",
      "Página com layout mobile-first",
      "Página com formulário estilizado",
      "Página com barra de navegação fixa",
      "Página com efeito parallax",
      "Jogo da velha",
      "Jogo de memória",
      "Quiz interativo com JavaScript e feedback visual",
      "Simulador de dados de formulário",
      "Validação de formulário",
      "Contador regressivo",
      "Gerador de senhas",
      "Simulador de sorteio",
      "Página com tabs interativas",
      "Página com contador de cliques",
      "Página com Bootstrap",
      "Página com Tailwind CSS",
      "Página com jQuery",
      "Página com Font Awesome",
      "Página com animações GSAP",
      "Página com Chart.js",
      "Página com ícones SVG animados",
      "Página com scroll suave",
      "Página com tooltips",
      "Página com pop-ups",
      "Página com drag and drop",
      "Página com barra de progresso",
      "Página com notificações",
      "Página com tema dinâmico",
      "Tema claro/escuro com persistência via localStorage",
      "Página com menu hamburguer",
      "Página com loading spinner",
      "Página com cards flip",
      "Página com efeito hover",
      "Página com botão que muda cor",
      "Simulador de app de clima (dados fixos)",
      "Simulador de app de notas",
      "Simulador de app de pomodoro",
      "Simulador de app de lista de compras",
      "Simulador de app de hábitos",
      "Simulador de app de calendário",
      "Simulador de app de finanças pessoais",
      "Simulador de app de leitura",
      "Simulador de app de música (sem áudio)",
      "Simulador de app de mensagens (estático)",
      "Modal customizado",
      "Tooltip customizado",
      "Accordion",
      "Tabs",
      "Slider",
      "Dropdown",
      "Menu lateral",
      "Card interativo",
      "Botão animado",
      "Input com máscara",
      "App que mostra piadas (API de piadas)",
      "App que mostra frases motivacionais",
      "App que mostra imagens de gatos",
      "App que mostra dados de Pokémon",
      "App que mostra dados de filmes",
      "App que mostra dados de países",
      "App que mostra dados de usuários",
      "App que mostra dados de livros",
      "App que mostra dados de moedas",
      "App que mostra dados de clima (API aberta)",
      "Projeto com estrutura de pastas organizada",
      "Projeto com README explicativo",
      "Projeto com favicon e manifest",
      "Projeto com semântica HTML",
      "Projeto com acessibilidade básica",
      "Projeto com SEO básico",
      "Projeto com layout flexbox",
      "Projeto com layout grid",
      "Projeto com media queries",
      "Projeto com variáveis CSS",
      "Página com easter egg escondido",
      "Página com tema retrô",
      "Página com tema futurista",
      "Página com tema minimalista",
      "Página com tema cyberpunk",
      "Página com tema natureza",
      "Página com tema espacial",
      "Página com tema de games",
      "Página com tema de filmes",
      "Página com tema de anime",
    ],
    pleno: [
      "Dashboard com gráficos dinâmicos usando Chart.js",
      "Aplicativo com React e consumo de API pública",
      "Sistema de busca com filtros e paginação",
      "Gerenciador de tarefas com drag-and-drop",
      "Navegação SPA com React Router e animações",
      "Dashboard interativo com gráficos usando Chart.js",
      "Sistema de autenticação com Firebase",
      "CRUD completo com React e API REST",
      "Aplicativo de clima com consumo de API externa",
      "Gerenciador de tarefas com React e localStorage",
      "Blog com React Router e Markdown",
      "Sistema de favoritos com persistência em IndexedDB",
      "Clone do Instagram com React e Firebase",
      "Aplicativo de receitas com filtros e busca",
      "Simulador de investimentos com gráficos dinâmicos",
      "E-commerce com carrinho e cálculo de frete",
      "Sistema de comentários com autenticação",
      "App de leitura com modo noturno e bookmarking",
      "App de quiz com ranking e pontuação",
      "App de notas com categorias e busca",
      "App de calendário com eventos recorrentes",
      "App de hábitos com gamificação",
      "App de finanças com gráficos e metas",
      "App de filmes com busca e favoritos",
      "App de livros com reviews e notas",
      "Landing page com animações GSAP e scroll reveal",
      "Site institucional com CMS headless (ex: Strapi)",
      "Portfólio com React e animações framer-motion",
      "Página com formulário validado via Yup",
      "Página com integração com API de pagamentos",
      "Página com integração com API de localização",
      "Página com integração com API de tradução",
      "Página com integração com API de imagens",
      "Página com integração com API de música",
      "Página com integração com API de vídeos",
      "Página com integração com API de notícias",
      "Página com integração com API de esportes",
      "Página com integração com API de criptomoedas",
      "Página com integração com API de transporte público",
      "Página com integração com API de previsão do tempo",
      "Página com integração com API de dados públicos",
      "Página com integração com API de redes sociais",
      "Página com integração com API de inteligência artificial",
      "Página com integração com API de geolocalização",
      "Página com integração com API de saúde",
      "Página com integração com API de educação",
      "Sistema de login com OAuth (Google, GitHub)",
      "Sistema de cadastro com validação de senha forte",
      "Sistema de recuperação de senha",
      "Sistema de upload de arquivos com preview",
      "Sistema de envio de e-mails com integração externa",
      "Sistema de notificações push",
      "Sistema de temas dinâmicos com context API",
      "Sistema de internacionalização (i18n)",
      "Sistema de acessibilidade com ARIA",
      "Sistema de SEO com React Helmet",
      "Sistema de roteamento dinâmico com React Router",
      "Sistema de lazy loading de componentes",
      "Sistema de infinite scroll",
      "Sistema de paginação de dados",
      "Sistema de filtros avançados",
      "Sistema de busca com debounce",
      "Sistema de autocomplete",
      "Sistema de drag and drop com react-beautiful-dnd",
      "Sistema de formulários com React Hook Form",
      "Sistema de testes com Jest e Testing Library",
      "Sistema de deploy com Vercel ou Netlify",
      "Sistema de CI/CD com GitHub Actions",
      "Sistema de versionamento com Git e GitHub",
      "Sistema de documentação com Storybook",
      "Sistema de design system com componentes reutilizáveis",
      "Sistema de gerenciamento de estado com Redux",
      "Sistema de gerenciamento de estado com Zustand",
      "Sistema de gerenciamento de estado com Context API",
      "Sistema de gerenciamento de estado com Recoil",
      "Sistema de gerenciamento de estado com MobX",
      "Sistema de gerenciamento de dados com SWR",
      "Sistema de gerenciamento de dados com React Query",
      "Sistema de gerenciamento de dados com Axios",
      "Sistema de gerenciamento de dados com Fetch API",
      "Sistema de gerenciamento de dados com GraphQL",
      "Sistema de gerenciamento de dados com Apollo Client",
      "Sistema de gerenciamento de dados com Firebase",
      "Sistema de gerenciamento de dados com Supabase",
      "Sistema de gerenciamento de dados com PocketBase",
      "Sistema de gerenciamento de dados com Hasura",
      "Sistema de gerenciamento de dados com Prisma",
      "Sistema de gerenciamento de dados com MongoDB Atlas",
      "Sistema de gerenciamento de dados com SQLite",
      "Sistema de gerenciamento de dados com PostgreSQL",
      "Sistema de gerenciamento de dados com MySQL",
      "Sistema de gerenciamento de dados com FaunaDB",
      "Sistema de gerenciamento de dados com Airtable",
      "Sistema de gerenciamento de dados com Google Sheets",
      "Sistema de gerenciamento de dados com LocalStorage",
      "Sistema de gerenciamento de dados com IndexedDB",
      "Sistema de gerenciamento de dados com Cookies",
      "Sistema de gerenciamento de dados com SessionStorage",
      "Sistema de gerenciamento de dados com WebSockets",
      "Sistema de gerenciamento de dados com SSE",
      "Sistema de gerenciamento de dados com REST",
      "Sistema de gerenciamento de dados com RPC",
      "Sistema de gerenciamento de dados com JSON Server",
      "Sistema de gerenciamento de dados com MirageJS",
      "Sistema de gerenciamento de dados com MSW (Mock Service Worker)",
      "Sistema de gerenciamento de dados com Firebase Emulator",
      "Sistema de gerenciamento de dados com GraphQL Mock",
      "Sistema de gerenciamento de dados com API externa simulada",
    ],
    senior: [
      "SPA com autenticação OAuth2 e gerenciamento de sessão",
      "Editor de código online com destaque de sintaxe",
      "PWA com cache offline, notificações push e instalação",
      "Visualizador de dados em tempo real com WebSocket",
      "Testes automatizados com Cypress e integração contínua",
      "SPA com autenticação OAuth2 e gerenciamento de sessão",
      "Editor de código online com destaque de sintaxe",
      "PWA com cache offline, notificações push e instalação",
      "Visualizador de dados em tempo real com WebSocket",
      "Testes automatizados com Cypress e integração contínua",
      "Dashboard com múltiplos gráficos e filtros dinâmicos",
      "Sistema de gerenciamento de usuários com permissões",
      "Painel administrativo com CRUD completo e logs",
      "Plataforma de cursos com vídeos, progresso e avaliações",
      "Sistema de pagamentos com integração Stripe",
      "Sistema de assinatura com planos e recorrência",
      "Sistema de upload de arquivos com drag-and-drop e preview",
      "Sistema de comentários com moderação e nested replies",
      "Sistema de notificações em tempo real",
      "Sistema de internacionalização com fallback inteligente",
      "Sistema de acessibilidade com navegação por teclado",
      "Sistema de SEO avançado com SSR e meta tags dinâmicas",
      "Sistema de deploy automatizado com CI/CD",
      "Sistema de monitoramento de erros com Sentry",
      "Sistema de análise de performance com Lighthouse",
      "Sistema de cache inteligente com SWR e fallback",
      "Sistema de autenticação com 2FA e recuperação de senha",
      "Sistema de integração com API GraphQL complexa",
      "Sistema de integração com CMS headless (Strapi, Sanity)",
      "Sistema de integração com Firebase + Firestore",
      "Sistema de integração com Supabase e autenticação",
      "Sistema de integração com Algolia para busca instantânea",
      "Sistema de integração com Elasticsearch",
      "Sistema de integração com GPT para geração de conteúdo",
      "Sistema de integração com API de vídeos (YouTube, Vimeo)",
      "Sistema de integração com API de mapas (Mapbox, Leaflet)",
      "Sistema de integração com API de pagamentos (Stripe, Mercado Pago)",
      "Sistema de integração com API de redes sociais (Twitter, LinkedIn)",
      "Sistema de integração com API de e-mail (SendGrid, Mailgun)",
      "Sistema de integração com API de imagens (Unsplash, Pexels)",
      "Sistema de integração com API de dados públicos (IBGE, OpenData)",
      "Sistema de integração com API de saúde (FHIR)",
      "Sistema de integração com API de educação (Google Classroom)",
      "Sistema de integração com API de transporte (Moovit, Transit)",
      "Sistema de integração com API de localização (Geolocation API)",
      "Sistema de integração com API de clima (OpenWeather)",
      "Sistema de integração com API de tradução (Google Translate)",
      "Sistema de integração com API de voz (Web Speech API)",
      "Sistema de integração com API de vídeo chamada (Agora, Twilio)",
      "Sistema de integração com API de autenticação biométrica",
      "Sistema de integração com API de reconhecimento facial",
      "Sistema de integração com API de OCR (Tesseract.js)",
      "Sistema de integração com API de leitura de código de barras",
      "Sistema de integração com API de escaneamento de QR Code",
      "Sistema de integração com API de blockchain (Web3.js)",
      "Sistema de integração com API de NFTs",
      "Sistema de integração com API de criptomoedas",
      "Sistema de integração com API de IA para recomendação",
      "Sistema de integração com API de IA para classificação",
      "Sistema de integração com API de IA para previsão",
      "Sistema de integração com API de IA para geração de imagem",
      "Sistema de integração com API de IA para chatbots",
      "Sistema de integração com API de IA para análise de sentimentos",
      "Sistema de integração com API de IA para transcrição de áudio",
      "Sistema de integração com API de IA para resumo de texto",
      "Sistema de integração com API de IA para tradução automática",
      "Sistema de integração com API de IA para detecção de objetos",
      "Sistema de integração com API de IA para segmentação de imagem",
      "Sistema de integração com API de IA para reconhecimento de voz",
      "Sistema de integração com API de IA para geração de música",
      "Sistema de integração com API de IA para geração de vídeo",
      "Sistema de integração com API de IA para criação de avatar",
      "Sistema de integração com API de IA para simulação de conversa",
      "Sistema de integração com API de IA para automação de tarefas",
      "Sistema de integração com API de IA para análise de código",
      "Sistema de integração com API de IA para refatoração de código",
      "Sistema de integração com API de IA para geração de testes",
      "Sistema de integração com API de IA para documentação automática",
      "Sistema de integração com API de IA para geração de README",
      "Sistema de integração com API de IA para geração de commits",
      "Sistema de integração com API de IA para sugestão de nomes",
      "Sistema de integração com API de IA para criação de wireframes",
      "Sistema de integração com API de IA para prototipagem",
      "Sistema de integração com API de IA para design responsivo",
      "Sistema de integração com API de IA para acessibilidade",
      "Sistema de integração com API de IA para performance",
      "Sistema de integração com API de IA para segurança",
      "Sistema de integração com API de IA para análise de logs",
      "Sistema de integração com API de IA para análise de métricas",
      "Sistema de integração com API de IA para geração de relatórios",
      "Sistema de integração com API de IA para análise de comportamento",
      "Sistema de integração com API de IA para personalização de conteúdo",
      "Sistema de integração com API de IA para recomendação de produtos",
      "Sistema de integração com API de IA para análise de mercado",
      "Sistema de integração com API de IA para previsão de demanda",
      "Sistema de integração com API de IA para análise de concorrência",
      "Sistema de integração com API de IA para geração de campanhas",
      "Sistema de integração com API de IA para otimização de anúncios",
      "Sistema de integração com API de IA para análise de ROI",
      "Sistema de integração com API de IA para análise de funil de vendas",
      "Sistema de integração com API de IA para segmentação de público",
      "Sistema de integração com API de IA para análise de churn",
      "Sistema de integração com API de IA para análise de retenção",
      "Sistema de integração com API de IA para análise de engajamento",
      "Sistema de integração com API de IA para análise de conversão",
      "Sistema de integração com API de IA para análise de tráfego",
    ],
  },
  backend: {
    junior: [
      "API REST com Node.js e Express",
      "CRUD simples com SQLite e validação básica",
      "Sistema de login com hash de senha (bcrypt)",
      "Gerador de senhas seguras via terminal",
      "API de clima que consome dados externos",
      "API REST simples com Node.js e Express",
      "CRUD básico com SQLite",
      "Sistema de login com hash de senha (bcrypt)",
      "Gerador de senhas seguras via terminal",
      "Conversor de moedas via terminal",
      "Calculadora de IMC via terminal",
      "Sistema de cadastro de usuários com validação",
      "API de frases motivacionais",
      "API de piadas aleatórias",
      "API de clima com dados fixos",
      "API de receitas com busca por ingrediente",
      "API de filmes com busca por título",
      "API de livros com busca por autor",
      "API de tarefas com status (feito/não feito)",
      "API de contatos com CRUD completo",
      "API de produtos com categorias",
      "API de usuários com filtros por idade",
      "API de posts com comentários",
      "API de perguntas e respostas",
      "API de notas escolares",
      "API de eventos com datas e locais",
      "API de músicas com gêneros",
      "API de mensagens com remetente e destinatário",
      "API de cursos com duração e descrição",
      "API de alunos com matrícula e notas",
      "API de professores com disciplinas",
      "API de empresas com setor e localização",
      "API de funcionários com cargo e salário",
      "API de clientes com histórico de compras",
      "API de pedidos com status e valor",
      "API de produtos com estoque",
      "API de categorias com subcategorias",
      "API de cidades com estados",
      "API de países com continentes",
      "API de moedas com cotação",
      "API de transporte com horários",
      "API de filmes com avaliação",
      "API de séries com temporadas",
      "API de livros com resenhas",
      "API de jogos com plataforma",
      "API de esportes com regras",
      "API de animais com habitat",
      "API de plantas com tipo e clima",
      "API de receitas com tempo de preparo",
      "API de exercícios com grupo muscular",
      "API de treinos com dias da semana",
      "API de hábitos com frequência",
      "API de metas com prazo",
      "API de finanças com entradas e saídas",
      "API de despesas com categorias",
      "API de orçamentos com limite",
      "API de investimentos com retorno esperado",
      "API de tarefas com prioridade",
      "API de projetos com status",
      "API de ideias com tags",
      "API de feedbacks com nota e comentário",
      "API de avaliações com estrelas",
      "API de produtos com imagens (URL)",
      "API de usuários com avatar",
      "API de login com token falso",
      "API com autenticação básica (sem JWT)",
      "API com rotas protegidas por senha",
      "API com middleware de log",
      "API com middleware de validação",
      "API com middleware de autenticação",
      "API com middleware de erro",
      "API com CORS configurado",
      "API com rate limit básico",
      "API com documentação em README",
      "API com estrutura MVC simples",
      "API com estrutura de pastas organizada",
      "API com banco de dados local (JSON)",
      "API com banco de dados SQLite",
      "API com banco de dados MongoDB local",
      "API com banco de dados PostgreSQL local",
      "API com banco de dados MySQL local",
      "API com conexão via Knex.js",
      "API com conexão via Sequelize",
      "API com conexão via Mongoose",
      "API com conexão via Prisma",
      "API com testes básicos com Jest",
      "API com testes básicos com Mocha",
      "API com testes básicos com Supertest",
      "API com logs em arquivo",
      "API com logs no console colorido",
      "API com logs com Winston",
      "API com logs com Morgan",
      "API com deploy no Render",
      "API com deploy no Railway",
      "API com deploy no Vercel (via serverless)",
      "API com deploy no Netlify Functions",
      "API com deploy no GitHub Pages (mock)",
      "API com deploy no Glitch",
      "API com deploy no Heroku",
      "API com deploy no Replit",
      "API com deploy no Firebase Functions",
      "API com deploy no AWS Lambda (simples)",
      "API com deploy no Azure Functions",
      "API com deploy no Google Cloud Functions",
      "API com documentação Swagger (simples)",
      "API com Postman Collection exportada",
      "API com README explicando rotas",
      "API com exemplos de uso via curl",
      "API com exemplos de uso via fetch",
      "API com exemplos de uso via axios",
    ],
    pleno: [
      "Autenticação com JWT e refresh token",
      "Sistema de agendamento com PostgreSQL",
      "API com testes automatizados usando Jest",
      "Monitoramento de logs com Winston e Morgan",
      "Upload de arquivos com validação e armazenamento local",
      "API com autenticação JWT",
      "API com refresh token",
      "API com múltiplos níveis de acesso (admin, user)",
      "API com upload de arquivos (multer)",
      "API com envio de e-mail (nodemailer)",
      "API com integração com Stripe (pagamentos)",
      "API com integração com PayPal",
      "API com integração com Twilio (SMS)",
      "API com integração com WhatsApp",
      "API com integração com Telegram Bot",
      "API com integração com OpenAI",
      "API com integração com Google Maps",
      "API com integração com Google Calendar",
      "API com integração com Google Sheets",
      "API com integração com Google Drive",
      "API com integração com GitHub",
      "API com integração com Spotify",
      "API com integração com Twitter/X",
      "API com integração com Instagram (via Meta)",
      "API com integração com Firebase",
      "API com integração com MongoDB Atlas",
      "API com integração com PostgreSQL remoto",
      "API com integração com Redis",
      "API com cache de respostas",
      "API com filas de processamento (Bull)",
      "API com WebSockets (chat em tempo real)",
      "API com SSE (Server-Sent Events)",
      "API com GraphQL",
      "API com REST + GraphQL combinados",
      "API com versionamento de rotas",
      "API com rate limit avançado",
      "API com monitoramento de performance",
      "API com logs estruturados (Winston + Elastic)",
      "API com métricas Prometheus",
      "API com health check",
      "API com testes unitários e de integração",
      "API com CI/CD (GitHub Actions)",
      "API com deploy automatizado",
      "API com Docker",
      "API com Docker Compose (DB + App)",
      "API com Kubernetes básico",
      "API com autenticação OAuth2",
      "API com login via Google",
      "API com login via Facebook",
      "API com login via GitHub",
      "API com login via LinkedIn",
      "API com login via Apple",
      "API com login via Twitter",
      "API com autenticação multifator (2FA)",
      "API com recuperação de senha",
      "API com verificação de e-mail",
      "API com sistema de notificações",
      "API com sistema de favoritos",
      "API com sistema de curtidas",
      "API com sistema de seguidores",
      "API com sistema de comentários",
      "API com sistema de avaliações",
      "API com sistema de denúncias",
      "API com sistema de moderação",
      "API com sistema de banimento",
      "API com sistema de permissões",
      "API com sistema de auditoria",
      "API com sistema de logs por usuário",
      "API com sistema de histórico de ações",
      "API com sistema de agendamento",
      "API com sistema de recorrência",
      "API com sistema de pagamentos recorrentes",
      "API com sistema de assinatura",
      "API com sistema de cupons",
      "API com sistema de cashback",
      "API com sistema de pontos",
      "API com sistema de gamificação",
      "API com sistema de ranking",
      "API com sistema de conquistas",
      "API com sistema de desafios",
      "API com sistema de recompensas",
      "API com sistema de sorteios",
      "API com sistema de eventos",
      "API com sistema de RSVP",
      "API com sistema de check-in",
      "API com sistema de QR Code",
      "API com sistema de geolocalização",
      "API com sistema de rastreamento",
      "API com sistema de entregas",
      "API com sistema de estoque",
      "API com sistema de logística",
      "API com sistema de frete",
      "API com sistema de devolução",
      "API com sistema de garantia",
      "API com sistema de suporte",
      "API com sistema de tickets",
      "API com sistema de chat com IA",
      "API com sistema de recomendação",
      "API com sistema de busca avançada",
      "API com sistema de filtros dinâmicos",
      "API com sistema de exportação de dados",
      "API com sistema de importação de dados",
      "API com sistema de backup",
      "API com sistema de restore",
      "API com sistema de replicação",
      "API com sistema de escalabilidade",
      "API com sistema de alta disponibilidade",
      "API com sistema de failover",
      "API com sistema de balanceamento de carga",
    ],
    senior: [
      "Microserviços com Docker, Kafka e PostgreSQL",
      "Sistema de filas com RabbitMQ e workers",
      "API GraphQL com resolvers complexos",
      "Search engine com ElasticSearch",
      "Testes de carga com Artillery e métricas com Prometheus",
      "Sistema com arquitetura de microsserviços",
      "Sistema com arquitetura hexagonal",
      "Sistema com arquitetura limpa (Clean Architecture)",
      "Sistema com DDD (Domain-Driven Design)",
      "Sistema com CQRS (Command Query Responsibility Segregation)",
      "Sistema com Event Sourcing",
      "Sistema com mensageria via RabbitMQ",
      "Sistema com mensageria via Kafka",
      "Sistema com mensageria via Redis Streams",
      "Sistema com orquestração de serviços",
      "Sistema com coreografias de eventos",
      "Sistema com API Gateway (ex: Kong, NGINX)",
      "Sistema com autenticação centralizada (Keycloak)",
      "Sistema com autorização baseada em roles e claims",
      "Sistema com segurança avançada (OWASP Top 10)",
      "Sistema com criptografia de dados sensíveis",
      "Sistema com assinatura digital",
      "Sistema com autenticação via certificado",
      "Sistema com autenticação biométrica (mock)",
      "Sistema com autenticação via hardware token (mock)",
      "Sistema com logs distribuídos (ELK Stack)",
      "Sistema com tracing distribuído (Jaeger)",
      "Sistema com observabilidade com OpenTelemetry",
      "Sistema com métricas via Prometheus + Grafana",
      "Sistema com deploy via Kubernetes",
      "Sistema com deploy via Helm",
      "Sistema com deploy via Terraform",
      "Sistema com deploy via Ansible",
      "Sistema com CI/CD via GitLab",
      "Sistema com CI/CD via Jenkins",
      "Sistema com CI/CD via CircleCI",
      "Sistema com CI/CD via Azure DevOps",
      "Sistema com testes de carga (Artillery)",
      "Sistema com testes de estresse (k6)",
      "Sistema com testes de segurança (OWASP ZAP)",
      "Sistema com testes de contrato (PACT)",
      "Sistema com testes de integração entre microsserviços",
      "Sistema com rollback automático",
      "Sistema com blue/green deployment",
      "Sistema com canary deployment",
      "Sistema com feature flags",
      "Sistema com AB testing",
      "Sistema com escalabilidade horizontal",
      "Sistema com escalabilidade vertical",
      "Sistema com replicação de banco de dados",
      "Sistema com particionamento de banco de dados",
      "Sistema com sharding",
      "Sistema com banco NoSQL (Cassandra)",
      "Sistema com banco orientado a grafos (Neo4j)",
      "Sistema com banco em memória (Redis)",
      "Sistema com banco time-series (InfluxDB)",
      "Sistema com banco columnar (ClickHouse)",
      "Sistema com cache distribuído",
      "Sistema com CDN para APIs",
      "Sistema com balanceamento de carga inteligente",
      "Sistema com failover automático",
      "Sistema com tolerância a falhas",
      "Sistema com auto healing",
      "Sistema com monitoramento de SLA",
      "Sistema com monitoramento de SLO",
      "Sistema com monitoramento de SLI",
      "Sistema com alertas inteligentes",
      "Sistema com dashboards em tempo real",
      "Sistema com auditoria completa",
      "Sistema com trilha de conformidade (LGPD/GDPR)",
      "Sistema com anonimização de dados",
      "Sistema com pseudonimização de dados",
      "Sistema com controle de acesso granular",
      "Sistema com segregação de dados por cliente",
      "Sistema com multitenancy",
      "Sistema com billing por uso",
      "Sistema com rate limit por cliente",
      "Sistema com throttling dinâmico",
      "Sistema com sandbox para testes",
      "Sistema com ambiente de staging",
      "Sistema com ambiente de homologação",
      "Sistema com rollback por versão",
      "Sistema com versionamento de banco",
      "Sistema com migração automática de schema",
      "Sistema com rollback de schema",
      "Sistema com validação de schema",
      "Sistema com API pública e privada",
      "Sistema com SDK para clientes",
      "Sistema com documentação OpenAPI",
      "Sistema com documentação interativa (Swagger UI)",
      "Sistema com portal de desenvolvedores",
      "Sistema com analytics de uso da API",
      "Sistema com billing por endpoint",
      "Sistema com precificação dinâmica",
      "Sistema com integração com ERP",
      "Sistema com integração com CRM",
      "Sistema com integração com BI",
      "Sistema com integração com sistemas legados",
      "Sistema com proxy reverso",
      "Sistema com firewall de aplicação",
      "Sistema com WAF (Web Application Firewall)",
      "Sistema com autenticação federada",
      "Sistema com SSO (Single Sign-On)",
      "Sistema com SAML",
      "Sistema com OAuth2 + OpenID Connect",
      "Sistema com autenticação delegada",
      "Sistema com gestão de identidade",
    ],
  },
  fullstack: {
    junior: [
      "To-do list com React no front e Express no back",
      "Blog com painel admin básico e Markdown",
      "Sistema de login com validação e sessões",
      "App de receitas com upload de imagens",
      "Calculadora financeira com histórico",
      "To-do list com login",
      "Blog simples com posts",
      "Cadastro de usuários",
      "Calculadora de IMC com histórico",
      "Conversor de moedas",
      "Agenda de contatos",
      "Catálogo de filmes",
      "Sistema de receitas",
      "Quiz com pontuação",
      "Sistema de tarefas",
      "Notas escolares",
      "Eventos com calendário",
      "Livros com resenhas",
      "Músicas com player básico",
      "Login com JWT",
      "Cadastro com validação",
      "Produtos com categorias",
      "Comentários com moderação",
      "Mensagens entre usuários",
      "Feedback com estrelas",
      "Login via Google",
      "Perfil com avatar",
      "Posts com likes",
      "Favoritos com tags",
      "Busca com filtros",
      "Tarefas com drag-and-drop",
      "Hábitos com frequência",
      "Metas com progresso",
      "Finanças com gráficos",
      "Treinos com dias da semana",
      "Sistema de login e logout",
      "Sistema de cadastro com confirmação",
      "Sistema de perfil editável",
      "Sistema de posts com imagens",
      "Sistema de produtos com estoque",
      "Sistema de contatos com grupos",
      "Sistema de filmes com avaliação",
      "Sistema de livros com autores",
      "Sistema de receitas com tempo de preparo",
      "Sistema de tarefas com prioridade",
      "Sistema de eventos com localização",
      "Sistema de músicas com playlists",
      "Sistema de cursos com descrição",
      "Sistema de alunos com notas",
      "Sistema de professores com disciplinas",
      "Sistema de empresas com setor",
      "Sistema de funcionários com cargo",
      "Sistema de clientes com histórico",
      "Sistema de pedidos com status",
      "Sistema de categorias com subcategorias",
      "Sistema de cidades com estados",
      "Sistema de países com continentes",
      "Sistema de moedas com cotação",
      "Sistema de transporte com horários",
      "Sistema de séries com temporadas",
      "Sistema de jogos com plataforma",
      "Sistema de esportes com regras",
      "Sistema de animais com habitat",
      "Sistema de plantas com tipo",
      "Sistema de exercícios com grupo muscular",
      "Sistema de treinos com dias",
      "Sistema de hábitos com frequência",
      "Sistema de metas com prazo",
      "Sistema de finanças com entradas",
      "Sistema de despesas com categorias",
      "Sistema de orçamentos com limite",
      "Sistema de investimentos com retorno",
      "Sistema de tarefas com prioridade",
      "Sistema de projetos com status",
      "Sistema de ideias com tags",
      "Sistema de feedbacks com nota",
      "Sistema de avaliações com estrelas",
      "Sistema de produtos com imagens",
      "Sistema de usuários com avatar",
      "Sistema com autenticação básica",
      "Sistema com rotas protegidas",
      "Sistema com middleware de log",
      "Sistema com middleware de validação",
      "Sistema com middleware de autenticação",
      "Sistema com middleware de erro",
      "Sistema com CORS configurado",
      "Sistema com rate limit básico",
      "Sistema com documentação em README",
      "Sistema com estrutura MVC simples",
      "Sistema com estrutura de pastas organizada",
      "Sistema com banco de dados local",
      "Sistema com banco SQLite",
      "Sistema com banco MongoDB local",
      "Sistema com banco PostgreSQL local",
      "Sistema com banco MySQL local",
      "Sistema com conexão via Knex.js",
      "Sistema com conexão via Sequelize",
      "Sistema com conexão via Mongoose",
      "Sistema com conexão via Prisma",
      "Sistema com testes básicos com Jest",
      "Sistema com testes básicos com Mocha",
      "Sistema com testes básicos com Supertest",
      "Sistema com logs em arquivo",
      "Sistema com logs no console",
      "Sistema com deploy no Render",
      "Sistema com deploy no Railway",
      "Sistema com deploy no Vercel",
      "Sistema com deploy no Netlify",
      "Sistema com deploy no Glitch",
      "Sistema com deploy no Heroku",
      "Sistema com deploy no Replit",
    ],
    pleno: [
      "E-commerce com carrinho, login e banco de dados",
      "Plataforma de cursos com upload de vídeos",
      "Sistema de comentários com moderação",
      "Painel administrativo com gráficos e filtros",
      "Chat em tempo real com WebSocket",
      "E-commerce com carrinho e checkout",
      "Blog com painel administrativo",
      "Plataforma de cursos com vídeos e progresso",
      "Sistema de agendamento com calendário",
      "Chat em tempo real com WebSockets",
      "Login com OAuth2 (Google, GitHub)",
      "Pagamentos com Stripe",
      "Assinatura mensal com recorrência",
      "Marketplace com vendedores e compradores",
      "Gestão de tarefas com equipe e status",
      "CRM básico com clientes e histórico",
      "Controle financeiro pessoal com gráficos",
      "Controle de estoque com alertas",
      "Gestão de projetos com kanban",
      "Sistema de suporte com tickets",
      "Fórum com tópicos e respostas",
      "Blog com editor markdown",
      "Dashboard com gráficos interativos",
      "Login com autenticação de dois fatores (2FA)",
      "Notificações em tempo real",
      "Favoritos com categorias e tags",
      "Ranking com gamificação",
      "Desafios com conquistas",
      "Busca com autocomplete",
      "Perfil com edição e avatar",
      "Comentários com moderação e denúncia",
      "Avaliação com estrelas e feedback",
      "Cadastro com verificação de e-mail",
      "Exportação de dados em CSV",
      "Importação de dados via Excel",
      "Deploy com CI/CD no GitHub Actions",
      "Deploy com Docker e Docker Compose",
      "Deploy no Vercel + Render",
      "Deploy com ambiente de staging",
      "Sistema com autenticação via LinkedIn",
      "Sistema com autenticação via Facebook",
      "Sistema com autenticação via Apple",
      "Sistema com autenticação via Twitter",
      "Sistema com autenticação via Microsoft",
      "Sistema com autenticação via Discord",
      "Sistema com autenticação via Firebase",
      "Sistema com autenticação via Auth0",
      "Sistema com autenticação via Keycloak",
      "Sistema com integração com Google Maps",
      "Sistema com integração com Google Calendar",
      "Sistema com integração com Google Drive",
      "Sistema com integração com Google Sheets",
      "Sistema com integração com GitHub",
      "Sistema com integração com Spotify",
      "Sistema com integração com Twitter/X",
      "Sistema com integração com Telegram Bot",
      "Sistema com integração com WhatsApp",
      "Sistema com integração com Twilio (SMS)",
      "Sistema com integração com OpenAI",
      "Sistema com integração com ERP",
      "Sistema com integração com CRM",
      "Sistema com integração com BI",
      "Sistema com integração com sistemas legados",
      "Sistema com autenticação multifator",
      "Sistema com recuperação de senha",
      "Sistema com verificação de e-mail",
      "Sistema com sistema de notificações",
      "Sistema com sistema de favoritos",
      "Sistema com sistema de curtidas",
      "Sistema com sistema de seguidores",
      "Sistema com sistema de avaliações",
      "Sistema com sistema de denúncias",
      "Sistema com sistema de moderação",
      "Sistema com sistema de banimento",
      "Sistema com sistema de permissões",
      "Sistema com sistema de auditoria",
      "Sistema com sistema de histórico de ações",
      "Sistema com sistema de agendamento",
      "Sistema com sistema de recorrência",
      "Sistema com sistema de pagamentos recorrentes",
      "Sistema com sistema de assinatura",
      "Sistema com sistema de cupons",
      "Sistema com sistema de cashback",
      "Sistema com sistema de pontos",
      "Sistema com sistema de gamificação",
      "Sistema com sistema de ranking",
      "Sistema com sistema de conquistas",
      "Sistema com sistema de desafios",
      "Sistema com sistema de recompensas",
      "Sistema com sistema de sorteios",
      "Sistema com sistema de eventos",
      "Sistema com sistema de RSVP",
      "Sistema com sistema de check-in",
      "Sistema com sistema de QR Code",
      "Sistema com sistema de geolocalização",
      "Sistema com sistema de rastreamento",
      "Sistema com sistema de entregas",
      "Sistema com sistema de estoque",
      "Sistema com sistema de logística",
      "Sistema com sistema de frete",
      "Sistema com sistema de devolução",
      "Sistema com sistema de garantia",
      "Sistema com sistema de suporte",
      "Sistema com sistema de tickets",
      "Sistema com sistema de recomendação",
      "Sistema com sistema de busca avançada",
      "Sistema com sistema de filtros dinâmicos",
      "Sistema com sistema de backup",
      "Sistema com sistema de restore",
      "Sistema com sistema de replicação",
      "Sistema com sistema de escalabilidade",
      "Sistema com sistema de alta disponibilidade",
    ],
    senior: [
      "Plataforma de ensino com pagamentos, vídeos e painel admin",
      "Sistema de autenticação com 2FA e recuperação de senha",
      "App com CI/CD, testes automatizados e deploy em cloud",
      "CMS customizado com editor visual e controle de acesso",
      "Fullstack app com microserviços, cache, e escalabilidade horizontal",
      "Plataforma de e-commerce com microsserviços",
      "Sistema de gestão empresarial com módulos independentes",
      "Plataforma de ensino com trilhas, vídeos e certificações",
      "Sistema de agendamento com múltiplos fusos horários",
      "Sistema de chat com criptografia ponta-a-ponta",
      "Sistema de autenticação federada com SSO",
      "Sistema de pagamentos com split entre usuários",
      "Sistema de assinatura com billing dinâmico",
      "Sistema de marketplace com reputação e moderação",
      "Sistema de CRM com automações e funil de vendas",
      "Sistema de ERP com controle de estoque e financeiro",
      "Sistema de BI com dashboards e relatórios customizados",
      "Sistema de suporte com SLA e escalonamento",
      "Sistema de fórum com moderação distribuída",
      "Sistema de blog com editor colaborativo em tempo real",
      "Sistema de notificações com Web Push e fallback SMS",
      "Sistema de gamificação com ranking global",
      "Sistema de busca com ElasticSearch",
      "Sistema de recomendação com IA",
      "Sistema de deploy com Kubernetes e Helm",
      "Sistema com arquitetura limpa + DDD + CQRS",
      "Sistema com Event Sourcing e Kafka",
      "Sistema com GraphQL federado",
      "Sistema com API Gateway e rate limit por plano",
      "Sistema com autenticação multifator via hardware token",
      "Sistema com logs distribuídos via ELK Stack",
      "Sistema com tracing via OpenTelemetry",
      "Sistema com métricas via Prometheus + Grafana",
      "Sistema com CI/CD via GitLab + Docker",
      "Sistema com rollback automático e canary deploy",
      "Sistema com feature flags e A/B testing",
      "Sistema com escalabilidade horizontal e vertical",
      "Sistema com replicação e particionamento de banco",
      "Sistema com cache distribuído via Redis",
      "Sistema com CDN para assets e APIs",
      "Sistema com failover automático e auto healing",
      "Sistema com monitoramento de SLA/SLO/SLI",
      "Sistema com alertas inteligentes e dashboards",
      "Sistema com trilha de conformidade (LGPD/GDPR)",
      "Sistema com anonimização e pseudonimização de dados",
      "Sistema com segregação de dados por cliente (multitenancy)",
      "Sistema com billing por uso e precificação dinâmica",
      "Sistema com integração com ERP (SAP, Oracle)",
      "Sistema com integração com CRM (Salesforce)",
      "Sistema com integração com BI (Power BI, Tableau)",
      "Sistema com integração com sistemas legados via SOAP",
      "Sistema com proxy reverso e firewall de aplicação",
      "Sistema com WAF (Web Application Firewall)",
      "Sistema com autenticação via SAML e OpenID Connect",
      "Sistema com gestão de identidade via Keycloak",
      "Sistema com mensageria via RabbitMQ e Kafka",
      "Sistema com orquestração de microsserviços",
      "Sistema com coreografia de eventos",
      "Sistema com deploy em múltiplas regiões",
      "Sistema com balanceamento de carga inteligente",
      "Sistema com banco de dados orientado a grafos (Neo4j)",
      "Sistema com banco time-series (InfluxDB)",
      "Sistema com banco columnar (ClickHouse)",
      "Sistema com banco em memória (Redis)",
      "Sistema com banco NoSQL distribuído (Cassandra)",
      "Sistema com autenticação biométrica (mock)",
      "Sistema com autenticação por reconhecimento facial (mock)",
      "Sistema com autenticação por voz (mock)",
      "Sistema com assinatura digital e verificação",
      "Sistema com integração com blockchain (mock)",
      "Sistema com contratos inteligentes (mock)",
      "Sistema com auditoria completa e logs por usuário",
      "Sistema com histórico de ações e versionamento",
      "Sistema com backup automático e restore por versão",
      "Sistema com replicação entre data centers",
      "Sistema com deploy em edge computing",
      "Sistema com integração com dispositivos IoT (mock)",
      "Sistema com controle de acesso granular por recurso",
      "Sistema com gestão de permissões por grupo e função",
      "Sistema com painel administrativo com logs e métricas",
      "Sistema com portal de desenvolvedores e SDK",
      "Sistema com documentação interativa via Swagger",
      "Sistema com testes de contrato entre microsserviços",
      "Sistema com testes de carga e estresse (Artillery, k6)",
      "Sistema com testes de segurança (OWASP ZAP)",
      "Sistema com testes automatizados com cobertura",
      "Sistema com deploy automatizado com rollback",
      "Sistema com blue/green deployment",
      "Sistema com canary deployment por região",
      "Sistema com deploy em múltiplas clouds (AWS, Azure)",
      "Sistema com deploy em ambiente híbrido (cloud + local)",
      "Sistema com integração com serviços de IA (OpenAI, HuggingFace)",
      "Sistema com integração com serviços de tradução automática",
      "Sistema com integração com serviços de reconhecimento de imagem",
      "Sistema com integração com serviços de voz",
      "Sistema com integração com serviços de geolocalização",
      "Sistema com integração com serviços de mapas e rotas",
      "Sistema com integração com serviços de clima",
      "Sistema com integração com serviços de transporte",
      "Sistema com integração com serviços financeiros",
      "Sistema com integração com serviços de saúde (mock)",
      "Sistema com integração com serviços educacionais",
      "Sistema com integração com serviços de logística",
      "Sistema com integração com serviços de entrega",
      "Sistema com integração com serviços de rastreamento",
      "Sistema com integração com serviços de QR Code",
      "Sistema com integração com serviços de pagamento instantâneo (Pix)",
      "Sistema com integração com serviços bancários (Open Banking)",
    ],
  },
};

// Mapeamento de ícones por área
const icones = {
  frontend: "fa-paint-brush",
  backend: "fa-server",
  fullstack: "fa-layer-group",
};

const areaSelect = document.getElementById("area");
const nivelSelect = document.getElementById("nivel");
const ideiaEl = document.getElementById("ideia");

function gerarIdeia() {
  const area = areaSelect.value;
  const nivel = nivelSelect.value;

  const lista = ideias[area][nivel];
  const ideiaTexto = lista[Math.floor(Math.random() * lista.length)];
  const icone = icones[area];

  const ideiaHTML = `
    <i class="fas ${icone}" style="color:#00bcd4; margin-right:8px;"></i>
    <strong>${nivel.toUpperCase()} - ${area.toUpperCase()}</strong>: ${ideiaTexto}
  `;

  ideiaEl.innerHTML = ideiaHTML;
}
